// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy6y_gXOTntZJf4ZpuG-BsZZpOVT-VnN8',
    appId: '1:659304248390:web:ac2cd5fd4ef92aca394647',
    messagingSenderId: '659304248390',
    projectId: 'aquasenses',
    authDomain: 'aquasenses.firebaseapp.com',
    storageBucket: 'aquasenses.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMPEv46sYUI5R8-Bg9GPNgKNydi5Y54N4',
    appId: '1:659304248390:android:fb5ff3ceb19aea48394647',
    messagingSenderId: '659304248390',
    projectId: 'aquasenses',
    storageBucket: 'aquasenses.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlSOcYw2VBF-oT1sl5PwuVx3TseTlMLvc',
    appId: '1:659304248390:ios:9bb2b073a6a834a2394647',
    messagingSenderId: '659304248390',
    projectId: 'aquasenses',
    storageBucket: 'aquasenses.firebasestorage.app',
    iosBundleId: 'com.example.aquasenses',
  );
}
